[DRAFT] Adding minor tests to test_regtap.
astropy/pyvo pull request #427
Opened 2023-02-22 08:07 UTC by msdemlei

(in an attempt to tackle #425).

2023-04-26 18:08 UTC, bsipocz approved these changes
Thank you for looking into this!

2023-04-26 18:13 UTC, bsipocz requested changes
Actually, there is one point where a more pythonic testing could be used,  but I'm not fully aware of what actual input values we expect.

2023-04-26 18:13 UTC, bsipocz commented on pyvo/registry/regtap.py
> +        if val != val:
I'm not sure this is the best way to test for `np.nan`s, or what other values would you expect here?

(e.g. `np.isnan(val)` or `np.isfinite(val)` is a cleaner check for NaNs)

2023-04-27 06:23 UTC, msdemlei commented
On Wed, Apr 26, 2023 at 11:13:45AM -0700, Brigitta Sipőcz wrote:
> @bsipocz requested changes on this pull request.
> I'm not sure this is the best way to test for `np.nan`s, or what
> other values would you expect here?

Yeah, it's (possibly) NaNs (the universal null value for floats in
VOTables, whether or not we like that).  I had wanted to avoid
another import, and x!=x is a rather safe test for "you don't want to
confront normal user code with this" -- but yes, the intent is
clearer with numpy.isnan, so I've force-pushed a change to that
effect.

2023-04-27 20:21 UTC, bsipocz commented
> I had wanted to avoid another import

numpy is practically imported at that point with astropy

2023-04-27 20:22 UTC, bsipocz approved these changes

2023-04-27 20:22 UTC, merged