Updated SIA up-casing behavior
astropy/pyvo pull request #545
Opened 2024-05-06 18:53 UTC by d-giles

Modified the behavior of the SIA service where it would upcase all format keywords. Modified to upcase keywords "ALL", "METADATA", and "GRAPHIC", otherwise the parameter is lowercased. Unrecognized formats will be lowercased, but result in an error directing the user to give a recognized format. The format "GRAPHIC-xyz" keyword does not currently work even if type-cased correctly so this PR has commented out code which can be integrated if that is resolved.

2024-05-07 08:10 UTC, msdemlei submitted a review, later dismissed
As commented in #544, I think this is a welcome robustness patch.

You should address the style issues, though, and I think a changelog entry "More robust handling of SIA1 FORMAT" would be in order.  I am pretty sure that passing in bytes would have failed before anyway, so I don't think dropping it needs mentioning.

The failing tests look unrelated; I suppose we need to work on the robustness of the doctests...

Whoever merges this: My vote is that this should be squash-merged.

2024-05-07 08:10 UTC, msdemlei commented on pyvo/dal/sia.py
>          if isinstance(format_, (str, bytes)):
I think we can safely drop support for bytes here, while we are at it.  And I think what we should really be writing here is:

```
if not isinstance(format_, list):
    format_ = format_.split(",")
```

That way, we at least get less insane diagnostics if people pass in something else than lists or strings, and we support passing in list literals.

2024-05-07 16:11 UTC, d-giles commented on pyvo/dal/sia.py
> +        print("Set format")
yes, indeed

2024-05-08 17:15 UTC, bsipocz requested changes
Minor fixes: please remove the debug line, it should fix the test, and fix the style things. You can run `flake8 pyvo --count` locally to see what they are until the count drops down to 0.

Also, please rebase. Currently, you have each of the commits twice in this PR. A rebase workflow will help mainaining a clean commit history by not allowing multiple versions of the same branches entangled, and it also keeps a clean resolution for commit conflicts, too. I'm happy to walk you through a rebase if you want.

2024-05-08 17:15 UTC, bsipocz commented on pyvo/dal/sia.py
> +                normalized_formats += [user_input.upper()]
This is a bit bike-shedding as normalized_formats will never be a very long list where we need to optimize on whether a new copy is made or not or how many intermediate list instances are created, nevertheless I would  think the following is a cleaner logic, here and below, too:
```suggestion
                normalized_formats.append(user_input.upper)
```

2024-05-08 17:15 UTC, bsipocz commented on pyvo/dal/sia.py
> +        print("Set format")
please remove this, it will also help with making sure the doctests pass

2024-05-08 17:17 UTC, bsipocz commented
We don't need to worry about the changelog failure above, I can move the entry to the bugfix section when/if I'm cutting a bugfix release (not yet sure we will have that or go ahead with the feature release sometimes soon).

2024-05-08 20:40 UTC, bsipocz commented
@pllim - please add @d-giles to the org, so I don't need to approve CI after each commit

2024-05-08 20:57 UTC, pllim commented
Re: https://github.com/astropy/pyvo/pull/545#issuecomment-2101393540

Added. Hope it helps!

2024-05-22 01:53 UTC, bsipocz commented
Given the imminent 1.5.2 release, I go ahead and rebase this to rerun with a fixed CI.

2024-05-22 02:15 UTC, bsipocz approved these changes
All review comments have been addressed, so I'll merge once CI is all green.

Thank you @d-giles!

2024-05-22 02:23 UTC, merged